/**
 * T2 glyphs — icon geometry the spec carries, drawn as `Path2D`.
 *
 * A glyph is `{name, view_box, ink_box, parts: {name: {d, mode, fill_rule,
 * stroke_width, anchor, spin}}}`. Three of those fields are not decoration, and
 * each fails *silently* when it is wrong, which is why they are required rather
 * than defaulted:
 *
 * - `mode` — `Path2D` carries geometry and no style at all. The set these come
 *   from is stroke-only, so `ctx.fill()` on one draws a solid black blob.
 * - `fill_rule` — the same failure one level down: an icon whose holes are
 *   subpaths fills them in when `evenodd` is dropped.
 * - `parts` — separate `Path2D`s, so a part can be transformed on its own. This
 *   is the whole reason the glyph schema has parts: a car and its wheels merged
 *   into one path cannot have turning wheels.
 *
 * The geometry is generated by `tools/build_glyphs.py` into `assets/glyphs/`
 * and reaches the player inside the spec. Nothing here fetches: a spec that
 * drew differently depending on what else was on disk would not be a contract.
 *
 * Colour and line caps are absent from the schema on purpose and set here
 * instead — they belong to the theme layer, for the same reason `body.danger`
 * cannot be a frozen colour.
 */

/**
 * `glyph` object -> its parts with a `Path2D` each, built once.
 *
 * Keyed by the object rather than by name: two specs may carry different
 * geometry under the same name, and a name-keyed cache would draw the first
 * one's picture from the second one's spec.
 */
const PATHS = new WeakMap();

function partsOf(glyph) {
  let parts = PATHS.get(glyph);
  if (!parts) {
    parts = Object.entries(glyph.parts).map(([name, part]) => ({
      name,
      part,
      path: new Path2D(part.d),
    }));
    PATHS.set(glyph, parts);
  }
  return parts;
}

/**
 * Draw `glyph` centred on the current origin, fitted into `width` x `height`.
 *
 * Fitted by the smaller of the two ratios rather than stretched to the box: the
 * car's ink is wider than it is tall, so scaling to the body's width alone would
 * push the wheels outside the body.
 *
 * Fitted against `ink_box` and not `view_box`. The view box is the icon set's
 * design grid and it is padded — Tabler draws the car in x 3..21, y 6..19 of a
 * 24x24 grid — so fitting it draws the glyph smaller than the body that asked
 * for it, by however much the set pads. `ink_box` is measured at build time
 * (`tools/path_bbox.py`) and includes the stroke.
 */
export function drawGlyph(ctx, glyph, width, height, color) {
  const [inkX, inkY, inkWidth, inkHeight] = glyph.ink_box;
  const scale = Math.min(width / inkWidth, height / inkHeight);
  if (!(scale > 0)) return;

  ctx.save();
  // The ink box need not start at 0, so the glyph is centred against its own
  // middle rather than against `inkWidth / 2`.
  ctx.translate(-(inkX + inkWidth / 2) * scale, -(inkY + inkHeight / 2) * scale);
  ctx.scale(scale, scale);
  // Round caps and joins are what the icon set was drawn for. `ctx.lineWidth` is
  // set inside the scaled frame, so a 2-unit stroke comes out 2 units thick on a
  // 24-unit icon however large the body is.
  ctx.lineCap = "round";
  ctx.lineJoin = "round";
  ctx.strokeStyle = color;

  for (const { part, path } of partsOf(glyph)) {
    if (part.mode === "fill") {
      ctx.fillStyle = color;
      ctx.fill(path, part.fill_rule);
    } else {
      ctx.lineWidth = part.stroke_width ?? 2;
      ctx.stroke(path);
    }
  }
  ctx.restore();
}
